### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Danilmikhan** [Hydraxous/UltraFunGuns#56]
**Describe the bug**
The mod doesnt work

**To Reproduce**
1. Go to 'any level'
2. Check weapons
3. No weapons

**Expected behavior**
Weapons.

**Logs (please complete the following information):**
[log.txt](https://github.com/Hydraxous/UltraFunGuns/files/13987203/log.txt)

**Additional context**
No ball hoop in the sandbox and configgy can see UFG with no errors.
Also keybinds dont work.

**Comment by Danilmikhan** [comment]
I think its because of mods, haven't checked though

**Comment by Danilmikhan** [comment]
Not because of other mods

**Comment by Hydraxous** [comment]
Thank you for providing the log. 

Can you verify that your game install is at least Patch 14c or newer? 

The error seems to be related to how UFG modifies parrying code. UFG-1.3.1 would be incompatible with versions older than Ultrakill patch 14c, since the parrying code was changed in that version.

**Comment by Danilmikhan** [comment]
if patch 14c is when violence released then yes im on patch 14c(mine is pirated)

**Comment by Danilmikhan** [comment]
i just checked and no im not on 14c

**Comment by Danilmikhan** [comment]
ig ill close it as completed and install ultrakill later
